### PR TITLE
chore: dependencies update

### PR DESCRIPTION
**Pull request by Mostafatalaat770**

### CODE REVIEW

**Comment by ignaciosantise** [comment]
hey @Mostafatalaat770 👋 thanks for the PR!

Just one comment, the `yarn.lock` file should only have changes related to the specific package updates. Can you revert that file, and run the updates again? After that, the lock file should have less changes.

Also, did you tested the changes with the example app? 

I'll test it too, and upload some screenshots.

**Comment by ignaciosantise** [comment]
@Mostafatalaat770 

The correct steps to follow should be:
1. Restore previous `yarn.lock`
2. Run `yarn add @walletconnect/react-native-compat@2.7.4`
3. Run `yarn add @walletconnect/universal-provider@2.7.4`

that way, the lock file will update the related packages only

**Review by ignaciosantise — APPROVED** [review]
🚀 It works well!

**Comment by Mostafatalaat770** [comment]
Perfect 🎉

**Pull request merged**
